---
title: Estimating words' age of acquisition
author: "Mika Braginsky and Daniel Yurovsky"
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: tango
    theme: spacelab
---

```{r setup, echo = FALSE}
library(knitr)
opts_chunk$set(message = FALSE, warning = FALSE, cache = TRUE)
```

```{r, cache = FALSE}
library(dplyr)
library(tidyr)
library(purrr)
library(readr)
library(ggplot2)
library(langcog)
library(wordbankr)
library(boot)
library(lazyeval)
library(robustbase)
theme_set(theme_mikabr())
```

Connect to the Wordbank database and pull out the raw data.
```{r, raw_data}
data_mode <- "local"

admins <- get_administration_data(mode = data_mode) %>%
  select(data_id, age, language, form)

items <- get_item_data(mode = data_mode) %>%
  mutate(num_item_id = as.numeric(substr(item_id, 6, nchar(item_id))),
         definition = tolower(definition))

words <- items %>%
  filter(type == "word", !is.na(uni_lemma), form == "WG",
         language %in% c("English", "Italian", "Norwegian", "Russian",
                         "Spanish", "Swedish", "Turkish"))

invalid_uni_lemmas <- words %>%
  group_by(uni_lemma) %>%
  filter(n() > 1,
         length(unique(lexical_class)) > 1) %>%
  arrange(language, uni_lemma)

get_inst_data <- function(inst_items) {
  inst_language <- unique(inst_items$language)
  inst_form <- unique(inst_items$form)
  inst_admins <- filter(admins, language == inst_language, form == inst_form)
  get_instrument_data(instrument_language = inst_language,
                      instrument_form = inst_form,
                      items = inst_items$item_id,
                      administrations = inst_admins,
                      iteminfo = inst_items,
                      mode = data_mode) %>%
    filter(!is.na(age)) %>%
    mutate(produces = !is.na(value) & value == "produces",
           understands = !is.na(value) & (value == "understands" | value == "produces")) %>%
    select(-value) %>%
    gather(measure, value, produces, understands) %>%
    mutate(language = inst_language,
           form = inst_form)
}

items_by_inst <- split(words, paste(words$language, words$form, sep = "_"))
raw_data <- map(items_by_inst, get_inst_data)
```

Fit models to predict each item's age of acquisition.
```{r, aoa_data}
fit_inst_measure_uni <- function(inst_measure_uni_data) {
  
  ages <- min(inst_measure_uni_data$age):max(inst_measure_uni_data$age)

  constants <- inst_measure_uni_data %>%
    select(language, form, measure, lexical_category, lexical_class, uni_lemma,
           words) %>%
    distinct()
  
  props <- inst_measure_uni_data %>%
    ungroup() %>%
    select(age, prop)
  
  tryCatch({
    model <- glmrob(cbind(num_true, num_false) ~ age, family = "binomial",
                    data = inst_measure_uni_data, y = TRUE)
    fit <- predict(model, newdata = data.frame(age = ages), se.fit = TRUE)
    aoa <- -model$coefficients[["(Intercept)"]] / model$coefficients[["age"]]
    fit_prop <- inv.logit(fit$fit)
    fit_se <- fit$se.fit
  }, error = function(e) {
    aoa <- fit <- fit_prop <- fit_se <- NA
  })
  
  data.frame(age = ages, fit_prop = fit_prop, fit_se = fit_se,
             aoa = aoa, language = constants$language, form = constants$form,
             measure = constants$measure,
             lexical_category = constants$lexical_category,
             lexical_class = constants$lexical_class,
             uni_lemma = constants$uni_lemma, words = constants$words) %>%
    left_join(props, by = "age")
}

fit_inst_measure <- function(inst_measure_data) {
  inst_measure_by_uni <- inst_measure_data %>%
    group_by(language, form, measure,
             lexical_category, lexical_class, uni_lemma,
             age, data_id) %>%
    summarise(uni_value = any(value),
              words = paste(definition, collapse = ", ")) %>%
    group_by(language, form, measure,
             lexical_category, lexical_class, uni_lemma, words,
             age) %>%
    summarise(num_true = sum(uni_value, na.rm = TRUE),
              num_false = n() - num_true,
              prop = mean(uni_value, na.rm = TRUE))
  inst_measure_by_uni %>%
    split(paste(.$lexical_category, .$lexical_class, .$uni_lemma)) %>%
    map(fit_inst_measure_uni) %>%
    bind_rows()
}

fit_inst <- function(inst_data) {
  print(unique(inst_data$language))
  inst_data %>%
    split(.$measure) %>%
    map(fit_inst_measure) %>%
    bind_rows()
}

prop_data <- map(raw_data, fit_inst)
all_prop_data <- bind_rows(prop_data)
#write_csv(all_prop_data, "app/all_prop_data.csv")
```

```{r}
all_prop_data %>%
  filter(language == "Swedish", measure == "understands", aoa < 0) %>%
#  filter(row_number() <= 9*16) %>%
         #uni_lemma %in% c("play pen", "tonight", "babysitter", "teacher")) %>%
         #uni_lemma %in% c("brother", "sister", "daddy", "mommy")) %>%
         #uni_lemma %in% c("person", "sister", "field", "peekaboo")) %>%
  ggplot(aes(x = age, y = prop)) +
    facet_wrap(~uni_lemma) +
    geom_point() +
    geom_line(aes(x = age, y = fit_prop)) +
    geom_hline(aes(yintercept = 0.5), color = "grey") +
    geom_vline(aes(xintercept = aoa), color = "grey") +
    geom_point(aes(x = aoa, y = 0.5), size = 4)
```

```{r}
aoa_data <- all_prop_data %>%
  filter(measure == "understands") %>%
  select(language, form, measure, lexical_category, lexical_class, uni_lemma, 
         words, aoa) %>%
  distinct()

aoa_validation <- aoa_data %>%
  mutate(valid_aoa = ifelse(!is.na(aoa) & aoa > 0 & aoa < 36,
                            "valid_aoa", "invalid_aoa")) %>%
  group_by(language, valid_aoa) %>%
  summarise(n = n()) %>%
  spread(valid_aoa, n, fill = 0) %>%
  mutate(percent_valid = valid_aoa / (valid_aoa + invalid_aoa))

aoa_data_filtered <- aoa_data %>%
  filter(aoa > 0 & aoa <= 30)

#write_csv(aoa_data_filtered, "aoa_data.csv")
```

```{r, fig.width=10, fig.height=8}
aoa_data_filtered %>%
  #filter(measure == "understands") %>%
  ggplot(aes(x = aoa, fill = language)) +
    facet_wrap(~language) +
    geom_histogram() +
    xlab("Age of Acquisition (months)") +
    ylab("Count") +
    scale_fill_solarized(guide = FALSE)
```
