---
title: <center>Predicting words' age of acquisition</center>
author: <center>Mika Braginsky, Daniel Yurovsky, Virginia Marchman, and Michael C. Frank</center>
date: <center>`r Sys.Date()`</center>
output:
  html_document:
    highlight: tango
    theme: spacelab
---

```{r setup, echo = FALSE}
library(knitr)
opts_chunk$set(message = FALSE, warning = FALSE, cache = TRUE, echo = FALSE, fig.align = "center")
```

```{r, cache = FALSE}
library(dplyr)
library(tidyr)
library(purrr)
library(readr)
library(ggplot2)
library(langcog)
library(wordbankr)
library(boot)
library(lazyeval)
library(broom)
library(directlabels)
library(lme4)
theme_set(theme_bw(base_size = 14))
font <- "Open Sans"
```

```{r}
# get items, words, and uni_lemmas

items <- get_item_data(mode = "local") %>%
  mutate(num_item_id = as.numeric(substr(item_id, 6, nchar(item_id))),
         definition = tolower(definition))

words <- items %>%
  filter(type == "word", !is.na(uni_lemma), form == "WG")

uni_lemmas <- words %>%
  filter(language == "English") %>%
  select(uni_lemma)

```

```{r}
# get AoA estimates
aoa_data <- read_csv("aoa_data.csv")
```

```{r}
# get frequency estimates

instruments <- aoa_data %>%
  select(language, form) %>%
  distinct()

inst_freqs <- function(language, form) {
  freq_file <- sprintf("predictors/frequency/freqs/freqs_%s.csv", tolower(language))
  if (file.exists(freq_file)) {
    read_csv(freq_file) %>%
      rename(definition = item) %>%
      mutate(language = language, form = form,
             defintion = tolower(definition))
  }
}

freqs <- map2(instruments$language, instruments$form, inst_freqs) %>%
  bind_rows() %>%
  right_join(words)
#  right_join(freq_words)

uni_freqs <- freqs %>%
  group_by(language, form, lexical_class, uni_lemma) %>%
  summarise(frequency = sum(frequency))
```

```{r}
# get estimates of valence, arousal, and dominance

valence <- read_csv("predictors/valence/valence.csv") %>%
  select(Word, V.Mean.Sum, A.Mean.Sum, D.Mean.Sum) %>%
  rename(word = Word, valence = V.Mean.Sum, arousal = A.Mean.Sum,
         dominance = D.Mean.Sum)

#missing_valence <- setdiff(uni_lemmas$uni_lemma, valence$word)
# write_csv(data.frame(uni_lemma = missing_babiness),
#           "predictors/valence/valence_replace.csv")

replacements_valence <- read_csv("predictors/valence/valence_replace.csv") %>%
  select(-lexical_class)
uni_valences <- uni_lemmas %>%
  left_join(replacements_valence) %>%
  rowwise() %>%
  mutate(word = if (!is.na(replacement) & replacement != "") replacement else uni_lemma) %>%
  select(-replacement) %>%
  left_join(valence)

#uni_valences <- read_csv("predictors/valence/uni_lemma_valence.csv")
```

```{r}
# get estimates of iconicity and babiness

babiness <- read_csv("predictors/babiness_iconicity/english_iconicity.csv") %>%
  group_by(word) %>%
  summarise(iconicity = mean(rating),
            babiness = mean(babyAVG))

#missing_babiness <- setdiff(uni_lemmas$uni_lemma, babiness$word)
# write_csv(data.frame(uni_lemma = missing_babiness),
#           "predictors/babiness_iconicity/babiness_iconicity_replace.csv")

replacements_babiness <- read_csv("predictors/babiness_iconicity/babiness_iconicity_replace.csv")
uni_babiness <- uni_lemmas %>%
  left_join(replacements_babiness) %>%
  rowwise() %>%
  mutate(word = if (!is.na(replacement) & replacement != "") replacement else uni_lemma) %>%
  select(-replacement) %>%
  left_join(babiness)

#uni_babiness <- read_csv("predictors/babiness_iconicity/babiness_iconicity.csv") 
```

```{r}
# get estimates of concreteness

concreteness <- read_csv("predictors/concreteness/concreteness.csv")

#missing_concreteness <- setdiff(uni_lemmas$uni_lemma, concreteness$Word)
# write_csv(data.frame(uni_lemma = missing_concreteness),
#           "predictors/concreteness/concreteness_replace.csv")

replacements_concreteness <- read_csv("predictors/concreteness/concreteness_replace.csv")
uni_concreteness <- uni_lemmas %>%
  left_join(replacements_concreteness) %>%
  rowwise() %>%
  mutate(Word = if (!is.na(replacement) & replacement != "") replacement else uni_lemma) %>%
  select(-replacement) %>%
  left_join(concreteness) %>%
  rename(concreteness = Conc.M) %>%
  select(uni_lemma, concreteness)
```

```{r}
# get (English) phoneme and syllable counts
phonemes <- read_csv("predictors/phonemes/english_phonemes.csv") %>%
  mutate(num_syllables = unlist(map(strsplit(syllables, " "), length)),
         num_phonemes = nchar(gsub("[', ]", "", syllables))) %>%
  select(-phones, -syllables)
```

```{r}
# put together data and predictors
uni_joined <- aoa_data %>%
  left_join(uni_freqs) %>%
  left_join(uni_valences) %>%
  left_join(uni_babiness) %>%
  left_join(uni_concreteness) %>%
  left_join(phonemes) %>%
  mutate(frequency = log(frequency))
```

*  *  *  *

Analysis 1: English
-------------------

```{r}
english_predictors <- c("frequency", "num_syllables", "num_phonemes", "concreteness",
                        "valence", "arousal", "babiness", "iconicity") #"dominance",

woof_concreteness <- unique(uni_joined$concreteness[uni_joined$uni_lemma == "woof woof"])
mean_babiness <- mean(filter(uni_joined, language == "English")$babiness, na.rm = TRUE)
mean_iconicity <- mean(filter(uni_joined, language == "English")$iconicity, na.rm = TRUE)

english_data <- uni_joined %>%
  filter(language == "English", measure == "understands",
         !(uni_lemma %in% c("don't", "babysitter's name", "child's own name"))) %>%
  rowwise() %>%
  mutate(valence = if (is.na(valence)) 5 else valence,
         arousal = if (is.na(arousal)) 1 else arousal,
         concreteness = if (is.na(concreteness)) woof_concreteness else concreteness,
         babiness = if (is.na(babiness)) mean_babiness else babiness,
         iconicity = if (is.na(iconicity)) mean_iconicity else iconicity) %>%
  ungroup() %>%
  #  mutate(valence = abs(valence - 5)) %>%
  group_by(language, measure) %>%
  mutate_each_(funs(as.numeric(scale(.))), english_predictors)

english_na_lemmas <- english_data %>%
  select_(.dots = c("uni_lemma", english_predictors)) %>%
  gather(predictor, value, -uni_lemma) %>%
  filter(is.na(value)) %>%
  group_by(uni_lemma) %>%
  summarise(num_na = n(), na_preds = paste(predictor, collapse = ", "))
```

```{r}
english_model_data <- english_data %>%
  filter(!is.na(frequency)) %>% # complete.cases(.))
  mutate(lexical_class = factor(lexical_class,
                                levels = c("nouns", "adjectives", "verbs",
                                           "function_words", "other"),
                                labels = c("Nouns", "Adjectives", "Verbs",
                                           "Function Words", "Other")))

english_formula <- as.formula(
  sprintf("aoa ~ %s", paste(english_predictors, collapse = " + "))
)

english_model <- lm(english_formula, data = english_model_data)
english_predictions <- english_model_data
english_predictions$predicted_aoa <- english_model$fitted.values

#cor(english_predictions$aoa, english_predictions$predicted_aoa)

english_coef <- tidy(english_model) %>%
  filter(term != "(Intercept)")

english_predictors_ordered <- english_predictors %>%
  factor(levels = english_coef$term[order(abs(english_coef$estimate))])

english_predictor_levels <- english_coef$term[order(abs(english_coef$estimate),
                                                    decreasing = TRUE)]
english_coef <- english_coef %>%
  mutate(term = factor(term, levels = english_predictor_levels))
```

```{r, fig.width = 12, fig.height = 7}
english_plot_data <- english_data %>%
  gather_("predictor", "value", english_predictors) %>%
  mutate(predictor = factor(predictor, levels = english_predictor_levels),
         lexical_class = factor(lexical_class,
                                levels = c("nouns", "adjectives", "verbs",
                                           "function_words", "other"),
                                labels = c("Nouns", "Adjectives", "Verbs",
                                           "Function Words", "Other")))

ggplot(english_plot_data, aes(x = value, y = aoa, colour = lexical_class)) +
  facet_grid(lexical_class ~ predictor) +
  geom_point(cex = 0.7) +
  geom_smooth(method = "lm", se = FALSE, cex = 1) +
  scale_colour_solarized(name = "") +
  xlab("\nPredictor Z-Score") +
  ylab("Age of Acquisition (months)\n") +
  theme(text = element_text(family = font),
        legend.position = "bottom",
        legend.direction = "horizontal")
```

```{r, fig.width = 7, fig.height = 7}
ggplot(english_predictions, aes(x = predicted_aoa, y = aoa)) +
  geom_text(aes(label = uni_lemma, colour = lexical_class), cex = 4, show_guide = FALSE) +
  geom_smooth(aes(colour = lexical_class), weight = 1, method = "lm", se = FALSE) +
  geom_smooth(colour = "black", weight = 2, method = "lm") +
  scale_colour_solarized(name = "") +
  scale_x_continuous(name = "\nModel Predicted Age of Acquisition (months)",
                     limits = c(6, 27), breaks = seq(6, 26, by = 2)) +
  scale_y_continuous(name = "Age of Acquisition (months)\n",
                     limits = c(6, 27), breaks = seq(6, 26, by = 2)) +
  coord_fixed() +
  theme(text = element_text(family = font),
        panel.grid.minor = element_blank(),
        legend.position = c(0.12, 0.9),
        legend.background = element_rect(fill = "transparent"))
```

```{r, fig.width = 5, fig.height = 4}
ggplot(english_coef, aes(x = term, y = abs(estimate), fill = term)) +
  geom_bar(stat = "identity") +
  geom_linerange(aes(ymin = abs(estimate) - 1.96 * std.error,
                     ymax = abs(estimate) + 1.96 * std.error)) +
  scale_fill_solarized(guide = FALSE) +
  xlab("") +
  ylab("Coefficient Magnitude\n") +
  theme(text = element_text(family = font),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
english_predictor_means <- english_data %>%
  filter(aoa <= 25) %>%
  mutate(aoa = cut(floor(aoa), breaks = c(4, 8, 12, 16, 20, 24))) %>%
  gather_("predictor", "value", english_predictors) %>%
  group_by(predictor, aoa) %>%
  filter(!is.na(value)) %>%
  multi_boot_standard(column = "value")
```

```{r, fig.width = 10, fig.height = 3}
ggplot(english_predictor_means, aes(x = aoa, y = mean, color = predictor)) +
  facet_grid(. ~ predictor) +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper)) +
  geom_line(aes(group = predictor)) +
  scale_colour_solarized(guide = FALSE) +
  xlab("\nAge of Acquisition (months)") +
  ylab("Mean Predictor Z-Score\n") +
  theme(text = element_text(family = font),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 30, hjust = 1))
```

*  *  *  *

Analysis 2: Cross-Linguistic
----------------------------

```{r}
crossling_predictors <- c("frequency", "num_characters", "concreteness",
                          "valence", "arousal", "babiness")

woof_concreteness <- unique(uni_joined$concreteness[uni_joined$uni_lemma == "woof woof"])
mean_babiness <- mean(filter(uni_joined, language == "English")$babiness, na.rm = TRUE)
mean_iconicity <- mean(filter(uni_joined, language == "English")$iconicity, na.rm = TRUE)

num_characters <- function(words) {
  strsplit(words, ", ") %>%
    map(function(word_set) {
      word_set %>%
        unlist() %>%
        strsplit(" [(].*[)]") %>%
        unlist() %>%
        strsplit("/") %>%
        unlist() %>%
        nchar() %>%
        mean()
    }) %>%
    unlist()
}

crossling_data <- uni_joined %>%
  filter(measure == "understands",
         !(uni_lemma %in% c("don't", "babysitter's name", "child's own name"))) %>%
  rowwise() %>%
  mutate(valence = if (is.na(valence)) 5 else valence,
         arousal = if (is.na(arousal)) 1 else arousal,
         concreteness = if (is.na(concreteness)) woof_concreteness else concreteness,
         babiness = if (is.na(babiness)) mean_babiness else babiness,
         iconicity = if (is.na(iconicity)) mean_iconicity else iconicity,
         num_characters = num_characters(words)) %>%
  ungroup() %>%
  group_by(language, measure) %>%
  mutate_each_(funs(as.numeric(scale(.))), crossling_predictors)

crossling_na_lemmas <- crossling_data %>%
  select_(.dots = c("uni_lemma", crossling_predictors)) %>%
  gather_("predictor", "value", crossling_predictors) %>%
  filter(is.na(value)) %>%
  group_by(uni_lemma) %>%
  summarise(num_na = n(), na_preds = paste(predictor, collapse = ", "))
```

```{r}
crossling_model_data <- crossling_data %>%
  filter(!is.na(frequency)) %>%
  mutate(lexical_class = factor(lexical_class,
                                levels = c("nouns", "adjectives", "verbs",
                                           "function_words", "other"),
                                labels = c("Nouns", "Adjectives", "Verbs",
                                           "Function Words", "Other")))

crossling_model <- lmer(aoa ~ frequency + num_characters + concreteness + valence + 
                          arousal + babiness + (frequency | language) +
                          (num_characters | language) + (concreteness | language) +
                          (valence | language) + (arousal | language) + (babiness | language),
                        data = crossling_data)

crossling_coef <- data.frame(term = row.names(summary(crossling_model)$coefficients),
                             estimate = summary(crossling_model)$coefficients[,"Estimate"],
                             std.error = summary(crossling_model)$coefficients[,"Std. Error"],
                             row.names = NULL) %>%
  filter(term != "(Intercept)")

crossling_predictors_ordered <- crossling_predictors %>%
  factor(levels = crossling_coef$term[order(abs(crossling_coef$estimate))])

crossling_predictor_levels <- crossling_coef$term[order(abs(crossling_coef$estimate),
                                                        decreasing = TRUE)]
crossling_coef <- crossling_coef %>%
  mutate(term = factor(term, levels = crossling_predictor_levels))
```

```{r, fig.width = 5, fig.height = 4}
ggplot(crossling_coef, aes(x = term, y = abs(estimate), fill = term)) +
  geom_bar(stat = "identity") +
  geom_linerange(aes(ymin = abs(estimate) - 1.96 * std.error,
                     ymax = abs(estimate) + 1.96 * std.error)) +
  scale_fill_solarized(guide = FALSE) +
  xlab("") +
  ylab("Coefficient Magnitude\n") +
  theme(text = element_text(family = font),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
joined_coef <- bind_rows(mutate(english_coef, type = "English"),
                         mutate(crossling_coef, type = "Cross-Linguistic")) %>%
  mutate(type = factor(type, levels = c("English", "Cross-Linguistic")),
         term = factor(term, levels = c(english_predictor_levels, "num_characters")))
```

```{r, fig.width = 7, fig.height = 4}
ggplot(joined_coef, aes(x = term, y = abs(estimate), fill = term)) +
  facet_wrap("type", scales = "free_x") +
  geom_bar(stat = "identity") +
  geom_linerange(aes(ymin = abs(estimate) - 1.96 * std.error,
                     ymax = abs(estimate) + 1.96 * std.error)) +
  scale_fill_solarized(guide = FALSE) +
  xlab("") +
  ylab("Coefficient Magnitude\n") +
  theme(text = element_text(family = font),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
crossling_predictor_means_by_lang <- crossling_data %>%
  filter(aoa <= 25) %>%
  mutate(aoa = cut(floor(aoa), breaks = c(4, 8, 12, 16, 20, 24))) %>%
  gather_("predictor", "value", crossling_predictors) %>%
  group_by(language, predictor, aoa) %>%
  filter(!is.na(value)) %>%
  multi_boot_standard(column = "value")
```

```{r, fig.width = 10, fig.height = 4}
crossling_predictor_means_by_lang %>%
  ungroup() %>%
  mutate(predictor = factor(predictor, levels = c(english_predictor_levels,
                                                  "num_characters"))) %>%
  ggplot(aes(x = aoa, y = mean, color = language)) +
  facet_grid(. ~ predictor) +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper)) +
  geom_line(aes(group = language)) +
  scale_colour_solarized(name = "") +
  xlab("\nAge of Acquisition (months)") +
  ylab("Mean Predictor Z-Score\n") +
  theme(text = element_text(family = font),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 30, hjust = 1),
        legend.position = "bottom",
        legend.direction = "horizontal")
```

```{r}
crossling_predictor_means <- crossling_data %>%
  filter(aoa <= 25) %>%
  mutate(aoa = cut(floor(aoa), breaks = c(4, 8, 12, 16, 20, 24))) %>%
  gather_("predictor", "value", crossling_predictors) %>%
  group_by(predictor, aoa) %>%
  filter(!is.na(value)) %>%
  multi_boot_standard(column = "value")
```

```{r, fig.width = 10, fig.height = 3}
crossling_predictor_means %>%
  ungroup() %>%
  mutate(predictor = factor(predictor, levels = c(english_predictor_levels,
                                                  "num_characters"))) %>%
  ggplot(aes(x = aoa, y = mean, color = predictor)) +
  facet_grid(. ~ predictor) +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper)) +
  geom_line(aes(group = predictor)) +
  scale_colour_solarized(guide = FALSE) +
  xlab("\nAge of Acquisition (months)") +
  ylab("Mean Predictor Z-Score\n") +
  theme(text = element_text(family = font),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 30, hjust = 1))
```
