---
title: Predicting words' age of acquisition
author: "Mika Braginsky and Daniel Yurovsky"
date: "`r Sys.Date()`"
output:
html_document:
  highlight: tango
  theme: spacelab
---

```{r setup, echo = FALSE}
library(knitr)
opts_chunk$set(message = FALSE, warning = FALSE, cache = TRUE)
```

```{r, cache = FALSE}
library(dplyr)
library(tidyr)
library(purrr)
library(readr)
library(ggplot2)
library(langcog)
library(wordbankr)
library(boot)
theme_set(theme_bw(base_size = 14))
font <- "Open Sans"
```

Connect to the Wordbank database and pull out the raw data.
```{r, raw_data}
admins <- get_administration_data(mode = "remote") %>%
  select(data_id, age, language, form)

items <- get_item_data(mode = "remote") %>%
  mutate(num_item_id = as.numeric(substr(item_id, 6, nchar(item_id))),
         definition = tolower(definition))

words <- items %>%
  filter(type == "word", !is.na(uni_lemma), form == "WG")

invalid_uni_lemmas <- words %>%
  group_by(uni_lemma) %>%
  filter(n() > 1,
         length(unique(lexical_class)) > 1) %>%
  arrange(language, uni_lemma)

get_inst_data <- function(inst_items) {
  inst_language <- unique(inst_items$language)
  inst_form <- unique(inst_items$form)
  inst_admins <- filter(admins, language == inst_language, form == inst_form)
  get_instrument_data(instrument_language = inst_language,
                      instrument_form = inst_form,
                      items = inst_items$item_id,
                      administrations = inst_admins,
                      iteminfo = inst_items,
                      mode = "remote") %>%
    filter(!is.na(age)) %>%
    mutate(produces = !is.na(value) & value == "produces",
           understands = !is.na(value) & (value == "understands" | value == "produces")) %>%
    select(-value) %>%
    gather(measure, value, produces, understands) %>%
    mutate(language = inst_language,
           form = inst_form)
}

items_by_inst <- split(words, paste(words$language, words$form, sep = "_"))
raw_data <- map(items_by_inst, get_inst_data)
```

Fit models to predict each item's age of acquisition.
```{r, aoa_data}
fit_inst_measure_uni <- function(inst_measure_uni_data) {
  ages <- min(inst_measure_uni_data$age):max(inst_measure_uni_data$age)
  model <- glm(cbind(num_true, num_false) ~ age, family = "binomial",
               data = inst_measure_uni_data)
  fit <- predict(model, newdata = data.frame(age = ages), se.fit = TRUE)
  aoa <- -model$coefficients[["(Intercept)"]] / model$coefficients[["age"]]
  constants <- inst_measure_uni_data %>%
    select(language, form, measure, lexical_category, lexical_class, uni_lemma,
           words) %>%
    distinct()
  data.frame(age = ages, fit_prop = inv.logit(fit$fit), fit_se = fit$se.fit,
             aoa = aoa, language = constants$language, form = constants$form,
             measure = constants$measure,
             lexical_category = constants$lexical_category,
             lexical_class = constants$lexical_class,
             uni_lemma = constants$uni_lemma, words = constants$words)
}

fit_inst_measure <- function(inst_measure_data) {
  inst_measure_by_uni <- inst_measure_data %>%
    group_by(language, form, measure,
             lexical_category, lexical_class, uni_lemma,
             age, data_id) %>%
    summarise(uni_value = any(value),
              words = paste(definition, collapse = ", ")) %>%
    group_by(language, form, measure,
             lexical_category, lexical_class, uni_lemma, words,
             age) %>%
    summarise(num_true = sum(uni_value, na.rm = TRUE),
              num_false = n() - num_true,
              prop = mean(uni_value, na.rm = TRUE))
  inst_measure_by_uni %>%
    split(paste(.$lexical_category, .$lexical_class, .$uni_lemma)) %>%
    map(fit_inst_measure_uni) %>%
    bind_rows()
}

fit_inst <- function(inst_data) {
  inst_data %>%
    split(.$measure) %>%
    map(fit_inst_measure) %>%
    bind_rows()
}

prop_data <- map(raw_data, fit_inst)
all_prop_data <- bind_rows(prop_data)
#write_csv(all_prop_data, "app/all_prop_data.csv")
```

```{r}
aoa_data <- all_prop_data %>%
  select(language, form, measure, lexical_category, lexical_class, uni_lemma, 
         words, aoa) %>%
  distinct() %>%
  filter(aoa > 5, aoa < 31)
```


Get frequency data.
```{r load_freqs}
instruments <- words %>%
  select(language, form) %>%
  distinct()

inst_freqs <- function(language, form) {
  freq_file <- sprintf("freqs/freqs_%s.csv", tolower(language))
  if (file.exists(freq_file)) {
    read_csv(freq_file) %>%
      rename(freq_item = item) %>%
      mutate(language = language, form = form)
  }
}

freq_words <- words %>%
  mutate(freq_item = unlist(map(strsplit(words$definition, " "), ~.x[1])))

freqs <- map2(instruments$language, instruments$form, inst_freqs) %>%
  bind_rows() %>%
  right_join(freq_words)

uni_freqs <- freqs %>%
  group_by(language, form, lexical_category, category, uni_lemma) %>%
  summarise(uni_freq = sum(frequency))
```

```{r load_valence}
uni_valences <- read_csv("predictors/uni_lemma_valence.csv") 
uni_babiness <- read_csv("predictors/iconicity_and_babiness.csv") 
```


```{r}
uni_joined <- aoa_data %>%
  left_join(uni_freqs) %>%
  left_join(uni_valences) %>%
  left_join(uni_babiness) %>%
  mutate(lexical_category = factor(lexical_category,
                                   levels = c("nouns", "predicates", 
                                              "function_words", "other"),
                                   labels = c("Nouns", "Predicates", 
                                              "Function Words", "Other"))) %>%
    gather(predictor, value, c(valence, arousal, dominance, babiness, iconicity))

class_means <- uni_joined %>%
  group_by(language, form, measure, predictor, lexical_class) %>%
  summarise(class_value = mean(value, na.rm = T))

lang_means <- class_means %>%
   summarise(lang_value = mean(class_value, na.rm = T))

get_predictor_value <- function(lemma_predictors) {
  lemma_class_means <- class_means %>%
    filter(language == unique(lemma_predictors$language),
           form  == unique(lemma_predictors$form), 
           measure == unique(lemma_predictors$measure),
           lexical_class == unique(lemma_predictors$lexical_class))
  
  lemma_lang_means <- lang_means %>%
    filter(language == unique(lemma_predictors$language),
           form  == unique(lemma_predictors$form), 
           measure == unique(lemma_predictors$measure))
  
  lemma_predictors %>%
    left_join(lemma_class_means) %>%
    left_join(lemma_lang_means) %>%
    rowwise() %>%
    mutate(value = if(!is.na(value)) value
           else if(!is.na(class_value)) class_value
           else lang_value)
}

uni_filled <- uni_joined %>%
  split(paste(.$language, .$form, .$measure, .$lexical_class, .$uni_lemma, sep = "_")) %>%
  map(get_predictor_value) %>%
  bind_rows() %>%

uni_spread <- uni_filled %>%
  select(-class_value, -lang_value) %>%
  spread(predictor, value)

# progress <- freqs %>%
#   group_by(language, form) %>%
#   summarise(num_items = n(),
#             num_uni_lemmas = sum(!is.na(uni_lemma)),
#             num_freqs = sum(!is.na(frequency)))
```

```{r}
# correlations <- uni_joined %>%
#   filter(!is.na(uni_freq)) %>%
#   split(paste(.$language, .$form, .$measure, .$lexical_category, sep = "_")) %>%
#   map(~lm(aoa ~ uni_freq, data = .)) %>%
#   map(summary) %>%
#   map_dbl("r.squared")

aoa_predictions <- uni_spread %>%
  filter(!is.na(babiness), !is.na(uni_freq), !is.na(valence), !is.na(arousal)) %>%
  split(paste(.$language, .$form, .$measure, .$lexical_category, sep = "_")) %>%
  map(function(model_data) {
    model <- lm(aoa ~ valence + arousal + babiness + log(uni_freq), data = model_data)
    model_data$predicted_aoa <- predict(model)
    model_data
  }) %>%
  bind_rows()

aoa_correlations <- aoa_predictions %>%
  group_by(language, form, measure, lexical_category) %>%
  summarise(correlation = cor(aoa, predicted_aoa)) %>%
  mutate(r = sprintf("r = %.3f", correlation))
#   
# rsq <- data.frame(language = unlist(map(strsplit(names(correlations), "_"), ~.x[1])),
#                   form = unlist(map(strsplit(names(correlations), "_"), ~.x[2])),
#                   measure = unlist(map(strsplit(names(correlations), "_"), ~.x[3])),
#                   lexical_category = unlist(map(strsplit(names(correlations), "_"), ~.x[4])),
# #                   rsq = sprintf("r² = %.3f", correlations),
#                   row.names = NULL)
```

```{r}
ggplot(filter(aoa_predictions, measure == "understands"),
       aes(x = predicted_aoa, y = aoa, colour = lexical_category)) +
  #facet_wrap(~language + form) +
  facet_grid(lexical_category ~ language) +
  geom_point(size = 0.8) +
  geom_abline(aes(slope = correlation, intercept = 0),
              data = filter(aoa_correlations, measure == "understands")) +
  geom_smooth(method = "lm", se = FALSE, size = 1) +
  scale_colour_solarized(guide = FALSE) +
   geom_text(aes(label = r, x = 20, y = 28),
            data = filter(aoa_correlations, measure == "understands"),
            size = 4, family = font) +
  scale_x_continuous(limits = c(0, 30)) +
  scale_y_continuous(limits = c(0, 30)) +
  xlab("\nModel Predicted Age of Acquisition") +
  ylab("Age of acquisition (months)\n") +
  theme_bw(base_size = 14) +
  theme(text = element_text(family = font))
```

```{r}
ggplot(filter(uni_joined, !is.na(arousal), measure == "understands"),
       aes(x = arousal, y = aoa, colour = lexical_category)) +
  #facet_wrap(~language + form) +
  facet_grid(lexical_category ~ language) +
  geom_point(size = 0.8) +
  geom_smooth(method = "lm", se = FALSE, size = 1) +
  geom_text(aes(label = rsq, x = 0.005, y = 28),
            data = filter(rsq, measure == "understands"), size = 4, family = font) +
  #scale_x_log10() +
  scale_colour_solarized(guide = FALSE) +
  xlab("\nLog frequency in child-directed speech") +
  ylab("Age of acquisition (months)\n") +
  theme_bw(base_size = 14) +
  theme(text = element_text(family = font))
```

```{r}
ggplot(filter(uni_joined, !is.na(babiness), measure == "understands"),
       aes(x = babiness, y = aoa, colour = lexical_category)) +
  #facet_wrap(~language + form) +
  facet_grid(lexical_category ~ language) +
  geom_point(size = 0.8) +
  geom_smooth(method = "lm", se = FALSE, size = 1) +
  geom_text(aes(label = rsq, x = 0.005, y = 28),
            data = filter(rsq, measure == "understands"), size = 4, family = font) +
  #scale_x_log10() +
  scale_colour_solarized(guide = FALSE) +
  xlab("\nLog frequency in child-directed speech") +
  ylab("Age of acquisition (months)\n") +
  theme_bw(base_size = 14) +
  theme(text = element_text(family = font))
```