---
title             : 'Supplemental information for "Consistency and variability in word learning across languages"'
shorttitle        : 'SI for "Word learning consistency and variability"'

author:
  - name          : Anonymized

affiliation:
  - institution   : ""

abstract          : ""

keywords          : 
bibliography      : [aoapred.bib]

figsintext        : yes
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : no

lang              : "english"
class             : "man"
output            : papaja::apa6_pdf
header-includes:
   - \usepackage{setspace}
   - \usepackage[font=small,labelfont=bf]{caption}
---

```{r setup, child="setup.Rmd"}
```

```{r model_checks, child="model_checks.Rmd"}
```

Age distributions
```{r age_dist, fig.height=6}
measure_admins <- admins %>%
  mutate(produces = TRUE, understands = form == "WG") %>%
  select(-form) %>%
  arrange(language) %>%
  mutate(language = str_replace(language, " \\(.*\\)", ""),
         language = fct_rev(fct_inorder(language)))

sample_sizes <- bind_rows(
  measure_admins %>% filter(produces) %>% mutate(measure = "Produces"),
  measure_admins %>% filter(understands) %>% mutate(measure = "Understands")
)

totals <- sample_sizes %>%
  group_by(measure) %>%
  mutate(max_age = max(age)) %>%
  group_by(language, measure, max_age) %>%
  summarise(n = n())

ggplot(sample_sizes, aes(x = age, y = language)) +
  facet_wrap(~measure, scales = "free_x") +
  geom_density_ridges(aes(fill = language)) +
  geom_label(aes(label = n, x = max_age), data = totals, vjust = 0, size = 3,
             nudge_y = 0.05, label.size = 0.2,
             label.padding = unit(0.1, "lines")) +
  labs(x = "Age (months)", y = "") +
  scale_fill_ptol(guide = FALSE)
```

Predictor distributions
```{r predictor_dist}
predictor_values <- uni_model_data %>%
  ungroup() %>%
  select(language, !!predictors) %>%
  distinct() %>%
  gather(predictor, value, !!predictors) %>%
  mutate(predictor = factor(predictor, levels = names(display_predictors),
                            labels = unname(display_predictors)),
         language = str_replace(language, " \\(.*\\)", ""),
         language = fct_inorder(language))


ggplot(predictor_values, aes(x = value, y = predictor, fill = predictor)) +
  facet_wrap(~language, nrow = 2) +
  geom_vline(xintercept = 0, colour = "darkgrey", linetype = "dashed") +
  geom_density_ridges(rel_min_height = 0.01, scale = 0.95, alpha = 0.7) +
  scale_x_continuous(expand = c(0.01, 0), limits = c(-3, 3)) +
  scale_y_discrete(expand = c(0.01, 0),
                   limits = rev(levels(predictor_values$predictor))) +
  scale_fill_ptol(guide = FALSE) +
    labs(x = "Scaled value", y = "")
```

Frequency distributions for open/closed class words
```{r freq_dist}
freq_values <- uni_model_data %>%
  ungroup() %>%
  select(language, lexical_classes, frequency) %>%
  distinct() %>%
  filter(!str_detect(lexical_classes, ","))  %>%
  mutate(language = str_replace(language, " \\(.*\\)", ""),
         language = fct_inorder(language),
         lexical_classes = fct_other(lexical_classes, keep = "function_words"),
         lexical_classes = fct_recode(lexical_classes,
                                      "Open class" = "Other",
                                      "Closed class" = "function_words"))

ggplot(freq_values, aes(x = frequency, y = lexical_classes)) +
  facet_wrap(~language, nrow = 2) +
  geom_vline(xintercept = 0, colour = "darkgrey", linetype = "dashed") +
  geom_density_ridges(aes(fill = lexical_classes), rel_min_height = 0.01,
                      scale = 0.95, alpha = 0.7) +
  scale_x_continuous(expand = c(0.01, 0), limits = c(-3, 3)) +
  scale_y_discrete(expand = c(0.01, 0)) +
  scale_fill_ptol(guide = FALSE) +
  labs(x = "Scaled frequency", y = "")

ggsave("freq_dist.png", width = 7, height = 5)
```

Paired prod/comp coefs
```{r prod_comp}
ggplot(filter(plt_lang_coefs, interaction == "main effect"),
       aes(x = term, y = estimate, colour = measure, shape = measure)) +
  facet_wrap(~language, nrow = 2) +
  coord_flip() +
  geom_pointrange(aes(ymin = estimate - 1.96 * std_error,
                      ymax = estimate + 1.96 * std_error),
                  position = position_jitter(width = 0.3, height = 0)) +
  geom_hline(yintercept = 0, color = "grey", linetype = "dashed") +
  scale_colour_ptol() +
  labs(x = "", y = "Coefficient estimate", colour = "", shape = "") +
  theme(legend.position = "top")

ggplot(filter(plt_lang_coefs, interaction == "main effect"),
       aes(x = estimate, y = term, colour = measure, shape = measure)) +
  facet_wrap(~language, nrow = 2) +
  geom_point() +
  # geom_pointrangeh(aes(xmin = estimate - 1.96 * std_error,
  #                     xmax = estimate + 1.96 * std_error),
  #                 position = position_jitter(width = 0, height = 0.3)) +
  geom_vline(xintercept = 0, color = "grey", linetype = "dashed") +
  scale_colour_ptol() +
  labs(y = "", x = "Coefficient estimate", colour = "", shape = "") +
  theme(legend.position = "top")
```

Coefs for each language with CIs
```{r by_lang_coefs}
ggplot(filter(plt_lang_coefs, measure == "produces",
              interaction == "main effect"),
       aes(x = estimate, y = term)) +
  facet_wrap(~language, nrow = 2) +
  geom_pointrangeh(aes(colour = term, shape = fct_rev(signif),
                       xmin = estimate - 1.96 * std_error,
                       xmax = estimate + 1.96 * std_error)) +
  geom_vline(xintercept = 0, color = "grey", linetype = "dashed") +
  scale_colour_ptol(guide = FALSE) +
  scale_shape_manual(values = c(19, 21), guide = FALSE) +
  labs(y = "", x = "Coefficient estimate")

ggplot(filter(plt_lang_coefs, measure == "understands",
              interaction == "main effect"),
       aes(x = estimate, y = term)) +
  facet_wrap(~language, nrow = 2) +
  geom_pointrangeh(aes(colour = term, shape = fct_rev(signif),
                       xmin = estimate - 1.96 * std_error,
                       xmax = estimate + 1.96 * std_error)) +
  geom_vline(xintercept = 0, color = "grey", linetype = "dashed") +
  scale_colour_ptol(guide = FALSE) +
  scale_shape_manual(values = c(19, 21), guide = FALSE) +
  labs(y = "", x = "Coefficient estimate")
```

Predictor correlations
```{r}
predictor_cors %>%
  mutate(predictor1 = predictor1 %>%
           factor(levels = predictors, labels = display_predictors[predictors]),
         predictor2 = predictor2 %>%
           factor(levels = rev(predictors),
                  labels = rev(display_predictors[predictors])),
         language = gsub("(.*) \\(.*\\)", "\\1", language)) %>%
ggplot(aes(x = predictor1, y = predictor2)) +
  facet_wrap(~language, nrow = 2) +
  coord_equal() +
  geom_tile(aes(fill = abs(correlation))) +
  geom_text(aes(label = round(correlation, 2)), size = 2.5) +
  scale_fill_gradient(low = ptol_pal()(2)[[1]], high = ptol_pal()(2)[[2]]) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) +
  labs(x = "", y = "", fill = "Correlation") +
  theme(legend.position = "top",
        legend.title = element_text(vjust = 0.8),
        axis.text.x = element_text(angle = 30, hjust = 1))
```

```{r vifs}
vifs %>%
  mutate(predictor = predictor %>%
           factor(levels = predictors,
                  labels = display_predictors[predictors]),
         language = gsub("(.*) \\(.*\\)", "\\1", language)) %>%
ggplot(aes(x = language, y = predictor)) +
  coord_equal() +
  geom_tile(aes(fill = vif)) +
  geom_text(aes(label = round(vif, 2)), size = 3) +
  scale_fill_gradient(low = ptol_pal()(2)[[1]], high = ptol_pal()(2)[[2]]) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) +
  labs(x = "", y = "", fill = "VIF") +
  theme(legend.position = "top",
        legend.title = element_text(vjust = 0.8),
        axis.text.x = element_text(angle = 30, hjust = 1))
```

```{r lexcat_consistency}
lexcat_coef_summary_means <- lexcat_coef_summary %>%
  group_by(lexical_category, measure) %>%
  summarise(mean_cor = mean(mean_cor))

ggplot(lexcat_coef_summary, aes(x = mean_cor, y = language)) +
  facet_grid(lexical_category ~ measure, labeller = as_labeller(label_caps)) +
  geom_vline(aes(xintercept = mean_cor), colour = "grey70", size = 0.4,
             data = lexcat_coef_summary_means) +
  geom_point(aes(colour = language), size = 2) +
  geom_rect(aes(xmin = ci_lower_cor, xmax = ci_upper_cor,
                ymin = as.numeric(language) + 0.4,
                ymax = as.numeric(language) - 0.4,
                fill = language),
            data = lexcat_baseline_coef_summary,
            alpha = .2, linetype = 0) +
  geom_segment(aes(x = mean_cor, xend = mean_cor,
                   y = as.numeric(language) + 0.4,
                   yend = as.numeric(language) - 0.4),
               data = lexcat_baseline_coef_summary,
               colour = "grey70") +
  scale_x_continuous(breaks = seq(0, 1, 0.2)) +
  labs(x = "Mean correlation with other languages' coefficients",
       y = "") +
  scale_colour_ptol(guide = FALSE) +
  scale_fill_ptol(guide = FALSE)
```
