```{r setup, include=FALSE, cache=FALSE} 
library(tidyverse)
library(widyr)

library(ggthemes)
library(ggstance)
library(ggdendro)
library(ggridges)
library(cowplot)

library(kableExtra)
library(knitr)
library(glue)
library(langcog)

opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = TRUE,
               out.width = "\\textwidth", dev = "png", fig.align = "center",
               dpi = 300, fig.path = "")
is_integer <- function(x) all(all.equal(x, as.integer(x)) == TRUE)
inline_hook <- function(x) {
  if (!is_integer(x) && is.numeric(x)) x <- sprintf("%.2f", round(x, 2))
  paste(as.character(x), collapse = ", ")
}
knit_hooks$set(inline = inline_hook)

theme_set(papaja::theme_apa(base_family = "Source Sans Pro"))
theme_update(strip.text.x = element_text(margin = margin(b = 8), face = "bold"),
             strip.text.y = element_text(margin = margin(l = 8), face = "bold"))
.grey <- "grey70"
.family <- theme_get()$text$family

label_caps <- function(value) {
  if_else(toupper(value) == value, value,
          paste0(toupper(substr(value, 1, 1)),
                 tolower(substr(value, 2, nchar(value))))) %>%
    str_replace_all("_", " ")
}
```

```{r load_data}
data_path <- "../data/"
data_files <- list.files(data_path, full.names = TRUE, recursive = TRUE) %>%
  discard(~str_sub(basename(.), 1, 1) == "_")
for (file in data_files) load(file)

num_langs <- n_distinct(lang_coefs$language)
predictors <- unique(lang_coefs$term)
num_coefs <- length(predictors)

display_predictors <- function(predictors) {
  predictors %>%
    str_replace("num", "number") %>% str_replace("phons", "phonemes") %>%
    map_chr(label_caps)
}
```

```{r coef_means}
mean_term_coefs <- lang_coefs %>%
  filter(effect == "main effect") %>%
  group_by(term) %>%
  summarise(mean_estimate = mean(estimate),
            n_sig = sum(signif),
            n_pos = sum(estimate > 0),
            n_neg = sum(estimate < 0)) %>%
  arrange(desc(abs(mean_estimate)))

mean_term_measure_coefs <- lang_coefs %>%
  filter(effect == "main effect") %>%
  group_by(measure, term) %>%
  summarise(mean_estimate = mean(estimate),
            n_sig = sum(signif),
            n_pos = sum(estimate > 0),
            n_neg = sum(estimate < 0)) %>%
  arrange(desc(abs(mean_estimate)))

mean_term_coef <- function(t, r = 2) {
 coef <- mean_term_coefs %>%
    filter(term == t) %>%
    pull(mean_estimate) %>%
    round(r)
 sprintf("$\\bar{\\beta} = %s$", coef)
}

mean_term_measure_coef <- function(meas, t) {
 coef <- mean_term_measure_coefs %>%
    filter(term == t, measure == meas) %>%
    pull(mean_estimate) %>%
    round(2)
 sprintf("$\\bar{\\beta} = %s$", coef)
}

most_opposite <- function(ex_terms) {
  terms <- mean_term_coefs %>%
    filter(!(term %in% ex_terms)) %>%
    mutate(larger = map2_dbl(n_pos, n_neg, max))
  min(terms$larger)
}

consistent_age <- lang_coefs %>%
  filter(effect == "interaction with age") %>%
  group_by(measure, term) %>%
  summarise(n_pos = sum(estimate > 0),
            n_neg = sum(estimate < 0)) %>%
  filter(n_pos >= 9 | n_neg >= 9)
```

```{r coefs}
coef_order <- mean_term_coefs %>% pull(term)

plt_lang_coefs <- lang_coefs %>%
  mutate(term = term %>% factor(levels = rev(coef_order)) %>%
           fct_relabel(display_predictors),
         signif = if_else(signif, "significant", "non-significant") %>%
           fct_rev(),
         language = language %>% str_remove(" \\(.*\\)") %>% as_factor())

plt_lexcat_coefs <- lexcat_coefs %>%
  mutate(term = term %>% factor(levels = rev(coef_order)) %>%
           fct_relabel(display_predictors),
         # signif = if_else(signif, "significant", "non-significant"),
         lexical_category = lexical_category %>%
           fct_relevel("nouns", "predicates"),
         language = language %>% str_remove(" \\(.*\\)") %>% as_factor()) %>%
  mutate_at(vars(contains("signif")),
            ~if_else(., "significant", "non-significant") %>% fct_rev())

ref_coefs <- plt_lang_coefs %>% filter(language == "English")

mean_lexcat <- lexcat_coefs %>%
  group_by(lexical_category, term) %>%
  summarise(mean_estimate = mean(estimate),
            n_pos = sum(estimate > 0),
            n_neg = sum(estimate < 0)) %>%
  arrange(desc(abs(mean_estimate)))

mean_lexcat_coef <- function(t, lc) {
 coef <- mean_lexcat %>%
    filter(term == t, lexical_category == lc) %>%
    pull(mean_estimate) %>%
    round(2)
 sprintf("$\\bar{\\beta} = %s$", coef)
}
```

```{r consistencies}
plt_coef_summary <- coef_summary %>%
  mutate(language = language %>% str_remove(" \\(.*\\)") %>% fct_rev())

plt_baseline_coef_summary <- baseline_coef_summary %>%
  mutate(language = language %>% str_remove(" \\(.*\\)") %>% fct_rev())

plt_lexcat_coef_summary <- lexcat_coef_summary %>%
  ungroup() %>%
  mutate(language = language %>% str_remove(" \\(.*\\)") %>% fct_rev(),
         lexical_category = lexical_category %>%
           fct_relevel("nouns", "predicates"))

plt_lexcat_baseline_coef_summary <- lexcat_baseline_coef_summary %>%
  ungroup() %>%
  mutate(language = language %>% str_remove(" \\(.*\\)") %>% fct_rev(),
         lexical_category = lexical_category %>%
           fct_relevel("nouns", "predicates"))

lexcat_mean_cor <- function(lc) {
  lexcat_coef_summary %>%
    group_by(lexical_category) %>%
    summarise(mean_cor = mean(mean_cor)) %>%
    filter(lexical_category == lc) %>%
    pull(mean_cor) %>%
    round(2)
}
```
